---
zookeeper:
  hosts: zookeeper

executor:
  enabled: true
  replicas: 2
  diskLimitPerJob: 250

merger:
  enabled: true
  replicas: 2

scheduler:
  enabled: true
  gearman:
    port: 4730
  tenantConfigPath: /etc/zuul/main.yaml

web:
  enabled: true
  replicas: 1
  port: 9000
  serviceType: ClusterIP

ingress:
  enabled: false

tenantConfig: {}
extraFiles: {}
